apiVersion: v1
kind: Service
metadata:
  name: gui-service
  labels:
    app: kafka-cqrs
spec:
  selector:
    app: kafka-cqrs
    service: gui-service
  ports:
  - name: gui-service-port
    protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-cqrs-gui-service
  labels:
    app: kafka-cqrs
    service: gui-service
spec:
  selector:
    matchLabels:
      app: kafka-cqrs
      service: gui-service
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka-cqrs
        service: gui-service
    spec:
      containers:
      - name: gui-service
        image: jojczykp.pl/kafka-cqrs/gui-service:0.0.1
        ports:
          - containerPort: 80
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 1
          periodSeconds: 1
