apiVersion: v1
kind: Service
metadata:
  name: notifier-service
  labels:
    app: kafka-cqrs
spec:
  selector:
    app: kafka-cqrs
    service: notifier-service
  ports:
  - name: notifier-service-port
    protocol: TCP
    port: 8081
    targetPort: 8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-cqrs-notifier-service
  labels:
    app: kafka-cqrs
    service: notifier-service
spec:
  selector:
    matchLabels:
      app: kafka-cqrs
      service: notifier-service
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka-cqrs
        service: notifier-service
    spec:
      initContainers:
      - name: wait-for-kafka
        image: busybox:1.35.0
        command: ['sh', '-c', 'HOST=kafka-service ; PORT=9092 ; until nc -w 5 -z ${HOST} ${PORT}; do echo Waiting for ${HOST}:${PORT}; sleep 2; done ; echo OK']
      containers:
      - name: notifier-service
        image: jojczykp.pl/kafka-cqrs/notifier-service:0.0.1
        ports:
          - containerPort: 8081
        readinessProbe:
          tcpSocket:
            port: 8081
          initialDelaySeconds: 1
          periodSeconds: 1
