apiVersion: v1
kind: Service
metadata:
  name: reader-service
  labels:
    app: kafka-cqrs
spec:
  selector:
    app: kafka-cqrs
    service: reader-service
  ports:
  - name: reader-service-port
    protocol: TCP
    port: 8082
    targetPort: 8082
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-cqrs-reader-service
  labels:
    app: kafka-cqrs
    service: reader-service
spec:
  selector:
    matchLabels:
      app: kafka-cqrs
      service: reader-service
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka-cqrs
        service: reader-service
    spec:
      initContainers:
      - name: wait-for-cassandra
        image: busybox:1.35.0
        command: ['sh', '-c', 'HOST=cassandra-service ; PORT=9042 ; until nc -w 5 -z ${HOST} ${PORT}; do echo Waiting for ${HOST}:${PORT}; sleep 2; done ; echo OK']
      containers:
      - name: reader-service
        image: jojczykp.pl/kafka-cqrs/reader-service:0.0.1
        ports:
          - containerPort: 8082
        readinessProbe:
          tcpSocket:
            port: 8082
          initialDelaySeconds: 1
          periodSeconds: 1
