plugins {
    id 'groovy'
    id 'application'
    alias(libs.plugins.spring.boot)
    alias(libs.plugins.spring.dependency.management)
}

compileJava {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

application {
    mainClass = 'pl.jojczykp.kafka_cqrs.producer.ProducerServiceMain'
}

tasks.register('buildDockerImage', Exec) {
    dependsOn distTar
    commandLine 'docker', 'build', '-t', "jojczykp.pl/kafka-cqrs/${project.name}:0.0.1", '.'
}

test {
    useJUnitPlatform()
}

clean.doFirst {
    delete fileTree(projectDir) { include '.attach_pid*' }
}

dependencies {
    annotationProcessor libs.lombok
    compileOnly libs.lombok

    implementation libs.spring.boot.starter.web
    implementation libs.spring.kafka
    implementation libs.guava
    implementation libs.jackson.datatype.jsr310

    testImplementation libs.groovy
    testImplementation libs.groovy.json
    testImplementation libs.commons.lang3
    testImplementation libs.spring.boot.starter.test
    testImplementation libs.spring.boot.starter.webmvc.test
    testImplementation libs.spock.spring
    testImplementation libs.junit.platform.engine
    testImplementation libs.junit.platform.launcher
}
