plugins {
    id 'groovy'
    id 'application'
    alias(libs.plugins.spring.boot)
    alias(libs.plugins.spring.dependency.management)
}

compileJava {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

application {
    mainClass = 'pl.jojczykp.kafka_cqrs.persister.PersisterServiceMain'
}

tasks.register('buildDockerImage', Exec) {
    dependsOn distTar
    executable 'sh'
    args '-c', "docker build -t jojczykp.pl/kafka-cqrs/${project.name}:0.0.1 ."
}

clean.doFirst {
    delete fileTree(projectDir) { include '.attach_pid*' }
}

test {
    useJUnitPlatform()
}

dependencies {
    annotationProcessor libs.lombok
    compileOnly libs.lombok

    implementation libs.spring.boot.starter
    implementation libs.spring.kafka
    implementation libs.spring.data.cassandra
    implementation(libs.cassandra.driver.core) {
        exclude group: 'com.datastax.oss', module: 'java-driver-shaded-guava'
    }

    implementation libs.guava

    testImplementation project(path: ':test-utils', configuration: 'default')
    testImplementation libs.groovy
    testImplementation libs.spring.boot.starter.test
    testImplementation libs.spock.spring
    testImplementation libs.junit.platform.engine
    testImplementation libs.junit.platform.launcher
    testImplementation libs.spring.kafka.test
    testImplementation libs.testcontainers
    testImplementation libs.testcontainers.cassandra
    testImplementation libs.testcontainers.spock
}
