buildscript {
    repositories {
        gradlePluginPortal()
        mavenLocal()
        mavenCentral()
        maven { url = 'https://repo.spring.io/snapshot' }
        maven { url = 'https://repo.spring.io/milestone' }
    }
}

wrapper {
    gradleVersion = '9.3.0'
}

allprojects {
    group = 'pl.jojczykp.kafka-cqrs'
}

subprojects {
    repositories {
        mavenLocal()
        mavenCentral()
        maven { url = 'https://repo.spring.io/snapshot' }
        maven { url = 'https://repo.spring.io/milestone' }
    }

    apply plugin: 'base'

    clean.doFirst {
        delete "${projectDir}/out/"
        delete "${projectDir}/target/"
        delete "${projectDir}/build/"
    }

    // Docker cleanup
    if (!project.getTasksByName('buildDockerImage', false).empty) {
        tasks.register('removeDockerImage', Exec) {
            executable 'sh'
            args '-c', "docker rmi -f jojczykp.pl/kafka-cqrs/${project.name}:0.0.1 || true"
        }
        clean.dependsOn removeDockerImage
    }
}
