plugins {
    id 'base'
}

tasks.register('npmInstall', Exec) {
    commandLine = ['npm', 'install']
}

tasks.register('npmBuild', Exec) {
    dependsOn npmInstall
    commandLine = ['npm', 'run-script', 'build']
}

tasks.register('buildDockerImage', Exec) {
    dependsOn npmBuild
    commandLine 'docker', 'build', '-t', "jojczykp.pl/kafka-cqrs/${project.name}:0.0.1", '.'
}

assemble.dependsOn npmBuild

clean.doFirst {
    delete 'dist'
}
