plugins {
    id 'base'
}

tasks.register('npmInstall', Exec) {
    executable 'sh'
    args '-c', 'npm install'
}

tasks.register('npmBuild', Exec) {
    dependsOn npmInstall
    executable 'sh'
    args '-c', 'npm run-script build'
}

tasks.register('buildDockerImage', Exec) {
    dependsOn npmBuild
    executable 'sh'
    args '-c', "docker build -t jojczykp.pl/kafka-cqrs/${project.name}:0.0.1 ."
}

build.dependsOn npmBuild

clean.doFirst {
    delete 'dist'
}
