plugins {
    id 'java'
    id 'org.springframework.boot' version '3.4.1'
    id 'io.spring.dependency-management' version '1.1.7'
}

// Disable bootJar since this is a library module
bootJar {
    enabled = false
}

jar {
    enabled = true
}

compileJava {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

dependencies {
    implementation 'org.springframework.kafka:spring-kafka'
    implementation 'org.springframework.kafka:spring-kafka-test'
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.18.2'

    implementation 'io.vertx:vertx-core:4.3.8'
}
