plugins {
    id 'groovy'
    alias(libs.plugins.spring.boot)
    alias(libs.plugins.spring.dependency.management)
}

// Disable bootJar since this is a test-only module
bootJar {
    enabled = false
}

jar {
    enabled = true
}

compileJava {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

clean.doFirst {
    delete fileTree(projectDir) { include '.attach_pid*' }
}

tasks.register('e2eTest', Test) {
    description = "Runs e2e Tests."
    testClassesDirs = sourceSets.test.output.classesDirs
    classpath = sourceSets.test.runtimeClasspath
    useJUnitPlatform()
}

test {
    enabled = false
}

dependencies {
    testImplementation project(path: ':test-utils', configuration: 'default')
    testImplementation libs.groovy
    testImplementation libs.spock.core
}