plugins {
    id 'groovy'
    id 'application'
    alias(libs.plugins.spring.boot)
    alias(libs.plugins.spring.dependency.management)
}

compileJava {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
    options.compilerArgs += ['-parameters']
}

application {
    mainClass = 'pl.jojczykp.kafka_cqrs.reader.ReaderServiceMain'
}

tasks.register('buildDockerImage', Exec) {
    dependsOn distTar
    executable 'sh'
    args '-c', "docker build -t jojczykp.pl/kafka-cqrs/${project.name}:0.0.1 ."
}

test {
    useJUnitPlatform()
}

dependencies {
    annotationProcessor libs.lombok
    compileOnly libs.lombok

    implementation libs.spring.boot.starter.web
    implementation libs.spring.data.cassandra

    testImplementation libs.groovy
    testImplementation libs.groovy.json
    testImplementation libs.spring.boot.starter.test
    testImplementation libs.spock.spring
    testImplementation libs.junit.platform.engine
    testImplementation libs.junit.platform.launcher
    testImplementation libs.testcontainers
    testImplementation libs.testcontainers.cassandra
    testImplementation libs.testcontainers.spock
    testImplementation libs.commons.lang3
}
