plugins {
    id 'groovy'
    id 'application'
    alias(libs.plugins.spring.boot)
    alias(libs.plugins.spring.dependency.management)
}

compileJava {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

application {
    mainClass = 'pl.jojczykp.kafka_cqrs.notifier.NotifierServiceMain'
}

tasks.register('buildDockerImage', Exec) {
    dependsOn distTar
    commandLine 'docker', 'build', '-t', "jojczykp.pl/kafka-cqrs/${project.name}:0.0.1", '.'
}

test {
    useJUnitPlatform()
}

clean.doFirst {
    delete "${projectDir}/.vertx/"
}

dependencies {
    annotationProcessor libs.lombok
    compileOnly libs.lombok

    implementation libs.spring.boot.starter
    implementation libs.spring.kafka
    implementation libs.vertx.core
    implementation libs.jackson.core
    implementation libs.jackson.databind
    implementation libs.jackson.annotations
    implementation libs.guava

    testImplementation project(path: ':test-utils', configuration: 'default')
    testImplementation libs.groovy
    testImplementation libs.spring.boot.starter.test
    testImplementation libs.spring.kafka.test
    testImplementation libs.spock.spring
    testImplementation libs.junit.platform.engine
    testImplementation libs.junit.platform.launcher
}
