plugins {
    id 'groovy'
    id 'application'
    id 'org.springframework.boot' version '3.4.1'
    id 'io.spring.dependency-management' version '1.1.7'
}

compileJava {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

application {
    mainClass = 'pl.jojczykp.kafka_cqrs.notifier.NotifierServiceMain'
}

tasks.register('buildDockerImage', Exec) {
    dependsOn distTar
    executable 'sh'
    args '-c', "docker build -t jojczykp.pl/kafka-cqrs/${project.name}:0.0.1 ."
}

test {
    useJUnitPlatform()
}

clean.doFirst {
    delete "${projectDir}/.vertx/"
}

dependencies {
    annotationProcessor 'org.projectlombok:lombok:1.18.36'
    compileOnly 'org.projectlombok:lombok:1.18.36'

    implementation 'org.springframework.boot:spring-boot-starter'
    implementation 'org.springframework.kafka:spring-kafka'
    implementation 'io.vertx:vertx-core:4.3.8'
    implementation 'com.fasterxml.jackson.core:jackson-core:2.18.2'
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.18.2'
    implementation 'com.fasterxml.jackson.core:jackson-annotations:2.18.2'
    implementation 'com.google.guava:guava:33.4.0-jre'

    testImplementation project(path: ':test-utils', configuration: 'default')
    testImplementation 'org.apache.groovy:groovy:4.0.25'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.kafka:spring-kafka-test'
    testImplementation 'org.spockframework:spock-spring:2.4-M4-groovy-4.0'
    testImplementation 'org.junit.platform:junit-platform-engine:1.11.3'
    testImplementation 'org.junit.platform:junit-platform-launcher:1.11.3'
}
